spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/money_backend
    username: money_backend
    password: money_backend
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    #      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
