spring:
  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://infomoney.cbsc4q0isjbr.eu-north-1.rds.amazonaws.com:5432/info_money}
    username: ${POSTGRES_USERNAME:info_money}
    password: ${POSTGRES_PASSWORD:info_money}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: ${HIBERNATE_MODE:update}
    #      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
